// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineFood1;

#nullable disable

namespace Onlinefood1.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20250221043547_ordermanagement")]
    partial class ordermanagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineFood1.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ordersOrderID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("ordersOrderID");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("OnlineFood1.Order", b =>
                {
                    b.HasOne("OnlineFood1.Order", "orders")
                        .WithMany()
                        .HasForeignKey("ordersOrderID");

                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
